from .idiotAgent import idiotModel
from .debugAgent import debugModel
from .dqn_agent import dqnModel
from .allfoldAgent import allFoldModel
from .allcallAgent import allCallModel
from .allinAgent import allinModel
from .allraiseAgent import allRaiseModel
from .A3C.A3C_agent import A3CAgent
from .MonteCarlo.agent import NpRandom